version: '3.9'
services:
  postgres:
    image: postgres:latest
    container_name: my-postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mdp
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    networks:
      - my-network

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: my-pgadmin-container
    environment:
      PGADMIN_DEFAULT_EMAIL: test@test.com
      PGADMIN_DEFAULT_PASSWORD: test
    ports:
      - "80:80"
    depends_on:
      - postgres
    networks:
      - my-network

networks:
  my-network:
